core/urls.py
from django.conf.urls import url, include
from core import views

urlpatterns = [
    url(r'^$', views.IndexView, name='index'),
]

donations/urls.py
from django.conf.urls import url, include
from donations import views

urlpatterns = [
    url(r'^$', views.donations, name='donation'),
    url(r'^adicionar/$', views.donations_add, name='donation_add'),
    url(r'^detalhes/(?P<pk>[\w_-]+)/$', views.donations_detail,
        name='donation_detail'),
    url(r'^editar/(?P<slug>[\w_-]+)/$', views.donations_update,
        name='donation_update'),
]

expenses/urls.py
from django.conf.urls import url, include
from expenses import views

urlpatterns = [
    url(r'^$', views.expenses, name='expense'),
    url(r'^adicionar/$', views.expenses_add, name='expense_add'),
    url(r'^detalhes/(?P<pk>[\w_-]+)/$', views.expenses_detail,
        name='expense_detail')
]

ong_joao_de_barro/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout
from core import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^entrar/$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^sair/$', logout, {'next_page': 'login'}, name='logout'),
    url(r'doacoes/', include('donations.urls', namespace='donations')),
    url(r'despesas/', include('expenses.urls', namespace='expenses')),
    url(r'conta/', include('accounts.urls', namespace='accounts')),
    url(r'usuarios/', include('users.urls', namespace='users')),
    url(r'^admin/', admin.site.urls),
]

donations/models.py
from django.db import models
from core.models import TimeStampedModel
from django.core.urlresolvers import reverse
from core.helpers.multiple_choices import DONATIONS_TYPE
from users.models import Donors


class Donations(TimeStampedModel):
    service_type = models.CharField('Tipo de serviço', max_length=12,
                                    choices=DONATIONS_TYPE,
                                    default='Recebimento')
    donor = models.ForeignKey(Donors, verbose_name='Doador')
    item = models.CharField('Item', max_length=100, default='')
    description = models.TextField('Descrição', blank=True)
    quantity = models.PositiveSmallIntegerField('Quantidade', default=0)

    def __str__(self):
        return str(self.service_type)

    class Meta:
        ordering = ['service_type']
        verbose_name = 'Doação'
        verbose_name_plural = 'Doações'

    def get_absolute_url(self):
        return reverse('donations:donation_detail', kwargs={'pk': self.pk})

donations/forms.py
# coding=utf-8
from django import forms
from donations.models import Donations, Donors


class DonationsAddForm(forms.ModelForm):
    class Meta:
        model = Donations
        fields = ['service_type', 'donor', 'item', 'description',
                  'quantity']
        readonly_fields = ('date')

#
# class ExpensesForm(forms.ModelForm):
#     def __init__(self, *args, **kwargs):
#         if not kwargs.get('initial'):
#             kwargs['initial'] = {}
#
#         if kwargs.get('instance'):
#             kwargs['initial'].update({'total': kwargs.get('instance').total})
#
#         super(ExpensesForm, self).__init__(*args, **kwargs)
#
#     total = forms.FloatField(widget=forms.NumberInput(
#             attrs={'readonly': 'readonly'}), required=False)
#
#     class Meta:
#         model = Expenses
#         exclude = []

donations/views.py
from django.db.models import Q
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, CreateView, UpdateView
from django.views.generic import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from donations.models import Donations
from donations.forms import DonationsAddForm


class IndexView(TemplateView):
    template_name = 'donations/index.html'


class DonationsListView(LoginRequiredMixin, ListView):
    template_name = 'donations/donations_list.html'
    context_object_name = 'donations'
    paginate_by = 10
    # queryset = Donations.objects.all().order_by('-date')

    def get_queryset(self):
        queryset = Donations.objects.all().order_by('-created_at')
        q = self.request.GET.get('q', '')
        if q:
            queryset = queryset.filter(
                Q(item__icontains=q) | Q(description__icontains=q) |
                Q(donor__name__icontains=q)  # used like foreign key
            )
        elif self.request.GET.get('service_type') == 'Doação':
            queryset = queryset.filter(service_type='Doação')
        elif self.request.GET.get('service_type') == 'Recebimento':
            queryset = queryset.filter(service_type='Recebimento')
        return queryset


class DonationsCreateView(LoginRequiredMixin, CreateView):
    model = Donations
    form_class = DonationsAddForm


class DonationsUpdateView(UpdateView):
    model = Donations
    template_name = 'donations/donations_update.html'
    fields = ['name', 'service_type', 'donor', 'quantity']
    success_url = reverse_lazy('donations:donation')

    def get_object(self):
        return self.object.all()


index = IndexView.as_view()
donations = DonationsListView.as_view()
donations_add = DonationsCreateView.as_view()
donations_update = DonationsUpdateView.as_view()
donations_detail = DetailView.as_view(model=Donations,
                                      context_object_name='donations')

donations/templates/donations/donations_detail.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %} Detalhes da Doação | {{ block.super}} {% endblock title %}

{% block spacename %} Detalhes da doação: {{object.item}} {% endblock spacename %}

{% block container %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6">
      <div class="panel-group">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title"> <a data-toggle="collapse" href="#collapseOne">
              <span class="fa fa-user"></span> Doações </a> </h4>
          </div>
          <div id="collapseOne" class="panel-collapse collapse in">
            <div class="panel-body">
              <div class="row">
                <table class="table table-user-information">
                  <tbody>
                    <tr>
                      <th class="col-md-3 text-justify"> Tipo de serviço </th>
                      <td>{{ donations.service_type }}</td>
                    </tr>
                    <tr>
                      <th class="text-justify"> Item </th>
                      <td>{{ donations.item }}</td>
                    </tr>
                    <tr>
                      <th class="text-justify">  Doador </th>
                      <td>{{ donations.donor }}</td>
                    </tr>
                      <tr>
                        <th class="text-justify"> Descrição </th>
                        <td>{{ donations.description }}</td>
                      </tr>
                      <tr>
                        <th class="text-justify"> Quantidade </th>
                        <td>{{ donations.quantity }}</td>
                      </tr>
                      <tr>
                        <th class="text-justify"> Data </th>
                        <td>{{ donations.created_at|date:"d/m/Y H:i A" }}</td>
                      </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <!-- button back -->
      <form class="navbar-form navbar-right" action="." method="get">
        <a href="{% url 'donations:donation' %}">
          <button type="button" class="btn btn-info btn-lg" style="width: 190px; height: 50px">
            <span class="glyphicon glyphicon-back"></span> Voltar
          </button>
        </a>
      </form>
    </div>
  </div>
</div>
{% endblock %}

donations/templates/donations/donations_form.html
{% extends "base.html" %}

{% load bootstrap %}
{% load widget_tweaks %}

{% block title %} Adicionar | {{ block.super}} {% endblock title %}

{% block spacename %} Adicionar {% endblock spacename %}

{% block container %}
  <form class="form-horizontal col-sm-5" action="." method="POST">
    {% csrf_token %}
    {{ form|bootstrap_horizontal:'col-lg-4' }}
	  <div class="form-group">
      <div class="col-sm-10 col-sm-offset-9">
        <button type="submit" class="btn btn-primary"> Salvar </button>
      </div>
    </div>
  </form>
  <div class="col-md-7">
    <!-- button back -->
    <form class="navbar-form navbar-right" action="." method="get">
      <a href="{% url 'donations:donation' %}">
        <button type="button" class="btn btn-info btn-lg" style="width: 190px; height: 50px">
          <span class="glyphicon glyphicon-back"></span> Voltar
        </button>
      </a>
    </form>
  </div>
{% endblock %}

donations/templates/donations/donations_list.html
{% extends "base.html" %}

{% load pagination %}

{% block title %} Lista de Doações | {{ block.super}} {% endblock title %}

{% block spacename %} Lista de Doações {% endblock spacename %}

{% block container %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <form class="navbar-form navbar-right" action="." method="get">
        <div class="col-md-12">
          <!-- add -->
          <a href="{% url 'donations:donation_add' %}">
            <button id="new_customer" type="button" class="btn btn-primary">
              <span class="glyphicon glyphicon-plus"></span> Adicionar
            </button>
          </a>
          <!-- search form -->
          <form class="navbar-form navbar-left" role="search" action="{% url 'expenses:expense' %}">
            <div class="form-group">
              <input name="q" type="text" class="form-control" placeholder="Pesquisar..." />
              <button type="submit" class="btn btn-success form-control"><span class="glyphicon glyphicon-search"></span></button>
            </div>
          </form>
        <br><br>
        <!-- search links -->
        <ul class="list-inline text-right">
          <li><a href="{% url 'donations:donation' %}"><span class="fa fa-star status-aprovado"></span> Todos</a></li>
          <li><a href="?service_type=Doação" name="doação"><span class="fa fa-circle"></span> Doação </a></li>
          <li><a href="?service_type=Recebimento" name="recebimento"><span class="fa fa-circle"></span> Recebimento </a></li>
        </ul>
      </div>
      </form>
    </div>
    <div class="col-md-12">
      <hr/>
    </div>
    <div class="col-md-12">
      {% if donations %}
    	<table class="table table-bordered">
    		<thead>
    			<tr>
    				<th>Item</th><th>Descrição</th><th>Tipo de Serviço</th><th>Doador</th><th>Qtd.</th><th>Data</th>
    			</tr>
    		</thead>
    		<tbody>
          {% for donation in donations %}
        			<tr>
                  <td><a href="{{ donation.get_absolute_url }}">{{donation.item}}</a></td>
                  <td>{{donation.description}}</td>
                  <td>{{donation.service_type}}</td>
                  <td>{{donation.donor}}</td>
                  <td>{{donation.quantity}}</td>
                  <td>{{donation.created_at|date:"d/m/Y H:i A"}}</td>
              </tr>
          {% endfor %}
    		</tbody>
    	</table>
      {% else %}
      <p class="alert alert-warning">Sem itens na lista.</p>
    {% endif %}
    </div>
  </div>
  <hr>
  <div>
    <h3><b>Total:</b> {{ donations|length }} doações</h3>
  </div>
  {% pagination request paginator page_obj%}
</div>
{% endblock %}