core/urls.py
from django.conf.urls import url, include
from core import views

urlpatterns = [
    url(r'^$', views.IndexView, name='index'),
]

expenses/urls.py
from django.conf.urls import url, include
from expenses import views

urlpatterns = [
    url(r'^$', views.expenses, name='expense'),
    url(r'^adicionar/$', views.expenses_add, name='expense_add'),
    url(r'^detalhes/(?P<pk>[\w_-]+)/$', views.expenses_detail,
        name='expense_detail')
]

ong_joao_de_barro/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout
from core import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^entrar/$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^sair/$', logout, {'next_page': 'login'}, name='logout'),
    url(r'doacoes/', include('donations.urls', namespace='donations')),
    url(r'despesas/', include('expenses.urls', namespace='expenses')),
    url(r'conta/', include('accounts.urls', namespace='accounts')),
    url(r'usuarios/', include('users.urls', namespace='users')),
    url(r'^admin/', admin.site.urls),
]

expenses/models.py
from django.db import models
from django.core.urlresolvers import reverse
from core.models import TimeStampedModel
from core.helpers.multiple_choices import EXPENSES_TYPE, UNIT_TYPE


class Expenses(TimeStampedModel):
    service_type = models.CharField('Tipo de serviço', max_length=12,
                                    choices=EXPENSES_TYPE, default='Compra')
    item = models.CharField('Item', max_length=100, default='')
    description = models.TextField('Descrição', blank=True)
    quantity = models.IntegerField('Quantidade', default=0)
    unit = models.CharField('Unidade', max_length=14, choices=UNIT_TYPE,
                            default='')
    price = models.DecimalField('Preço', max_digits=6, decimal_places=2,
                                default=0)

    @property
    def total(self):
        return self.quantity * self.price

    def __str__(self):
        return str(self.service_type)

    class Meta:
        ordering = ['service_type']
        verbose_name = 'Despesa'
        verbose_name_plural = 'Despesas'

    def get_absolute_url(self):
        return reverse('expenses:expense_detail', kwargs={'pk': self.pk})

expenses/forms.py
# coding=utf-8
from django import forms
from expenses.models import Expenses


class ExpensesAddForm(forms.ModelForm):
    class Meta:
        model = Expenses
        fields = ['service_type', 'item', 'description', 'quantity', 'unit',
                  'price']
        readonly_fields = ('date')

expenses/views.py
from django.db import models
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from expenses.models import Expenses
from expenses.forms import ExpensesAddForm


class ExpensesListView(LoginRequiredMixin, ListView):
    template_name = 'expenses/expenses_list.html'
    context_object_name = 'expenses'
    paginate_by = 10
    # queryset = Expenses.objects.all().order_by('-date')

    def get_queryset(self):
        queryset = Expenses.objects.all().order_by('-created_at')
        q = self.request.GET.get('q', '')
        if q:
            queryset = queryset.filter(
                models.Q(item__icontains=q) |
                models.Q(description__icontains=q)
                # models.Q(donors__name__icontains=q)  # used like foreign key
            )
        elif self.request.GET.get('service_type') == 'Aluguel':
            queryset = queryset.filter(service_type='Aluguel')
        elif self.request.GET.get('service_type') == 'Compra':
            queryset = queryset.filter(service_type='Compra')
        elif self.request.GET.get('service_type') == 'Pagamento':
            queryset = queryset.filter(service_type='Pagamento')
        return queryset


class ExpensesDetailView(LoginRequiredMixin, DetailView):
    model = Expenses
    context_object_name = 'expenses'


class ExpensesCreateView(LoginRequiredMixin, CreateView):
    model = Expenses
    form_class = ExpensesAddForm


expenses = ExpensesListView.as_view()
expenses_detail = ExpensesDetailView.as_view()
expenses_add = ExpensesCreateView.as_view()

expenses/templates/expenses/expenses_detail.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %} Detalhes da despesa | {{ block.super}} {% endblock title %}

{% block spacename %} Detalhes da despesa: {{object.item}} {% endblock spacename %}

{% block container %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6">
      <div class="panel-group">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title"> <a data-toggle="collapse" href="#collapseOne">
              <span class="fa fa-user"></span> Despesas </a> </h4>
          </div>
          <div id="collapseOne" class="panel-collapse collapse in">
            <div class="panel-body">
              <div class="row">
                <table class="table table-user-information">
                  <tbody>
                    <tr>
                      <th class="col-md-3 text-justify"> Tipo de serviço </th>
                      <td>{{ expenses.service_type }}</td>
                    </tr>
                    <tr>
                      <th class="text-justify"> Item </th>
                      <td>{{ expenses.item }}</td>
                    </tr>
                    <tr>
                      <th class="text-justify"> Descrição </th>
                      <td>{{ expenses.description }}</td>
                    </tr>
                    <tr>
                      <th class="text-justify"> Quantidade </th>
                      <td>{{ expenses.quantity }} {{ expenses.unit }}</td>
                    </tr>
                    <tr>
                      <th class="text-justify">  Preço </th>
                      <td>R$ {{ expenses.price }}</td>
                    </tr>
                    <tr>
                      <th class="text-justify">  Total </th>
                      <td>R$ {{ expenses.total }}</td>
                    </tr>
                    <tr>
                      <th class="text-justify"> Data </th>
                      <td>{{ expenses.created_at|date:"d/m/Y H:i A" }}</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <!-- button back -->
      <form class="navbar-form navbar-right" action="." method="get">
        <a href="{% url 'expenses:expense' %}">
          <button type="button" class="btn btn-info btn-lg" style="width: 190px; height: 50px">
            <span class="glyphicon glyphicon-back"></span> Voltar
          </button>
        </a>
      </form>
    </div>
  </div>
</div>
{% endblock %}

expenses/templates/expenses/expenses_form.html
{% extends "base.html" %}

{% load bootstrap %}
{% load widget_tweaks %}

{% block title %} Adicionar | {{ block.super}} {% endblock title %}

{% block spacename %} Adicionar {% endblock spacename %}

{% block container %}
  <form class="form-horizontal col-sm-5" action="." method="POST">
    {% csrf_token %}
    {{ form|bootstrap_horizontal:'col-lg-4' }}
	  <div class="form-group">
      <div class="col-sm-10 col-sm-offset-9">
        <button type="submit" class="btn btn-primary"> Salvar </button>
      </div>
    </div>
  </form>
  <div class="col-md-7">
    <!-- button back -->
    <form class="navbar-form navbar-right" action="." method="get">
      <a href="{% url 'expenses:expense' %}">
        <button type="button" class="btn btn-info btn-lg" style="width: 190px; height: 50px">
          <span class="glyphicon glyphicon-back"></span> Voltar
        </button>
      </a>
    </form>
  </div>
{% endblock %}

expenses/templates/expenses/expenses_list.html
{% extends "base.html" %}

{% load pagination %}

{% block title %} Lista de Despesas | {{ block.super}} {% endblock title %}

{% block spacename %} Lista de Despesas {% endblock spacename %}

{% block container %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <form class="navbar-form navbar-right" action="." method="get">
        <div class="col-md-12">
          <!-- add -->
          <a href="{% url 'expenses:expense_add' %}">
            <button id="new_customer" type="button" class="btn btn-primary">
              <span class="glyphicon glyphicon-plus"></span> Adicionar
            </button>
          </a>
          <!-- search form -->
          <form class="navbar-form navbar-left" role="search" action="{% url 'expenses:expense' %}">
  	        <div class="form-group">
	            <input name="q" type="text" class="form-control" placeholder="Pesquisar..." />
              <button type="submit" class="btn btn-success form-control"><span class="glyphicon glyphicon-search"></span></button>
            </div>
          </form>
          <br><br>
          <!-- Search links-->
          <ul class="list-inline text-right">
            <li><a href="{% url 'expenses:expense' %}"><span class="fa fa-star status-aprovado"></span> Todos</a></li>
            <li><a href="?service_type=Aluguel" name="aluguel"><span class="fa fa-circle"></span> Aluguel</a></li>
            <li><a href="?service_type=Compra" name="compra"><span class="fa fa-circle"></span> Compra</a></li>
            <li><a href="?service_type=Pagamento" name="pagamento"><span class="fa fa-circle"></span> Pagamento</a></li>
          </ul>
        </div>
      </form>
    </div>
    <div class="col-md-12">
      <hr/>
    </div>
    <div class="col-md-12">
      {% if expenses %}
    	<table class="table table-bordered">
    		<thead>
    			<tr>
    				<th>Item</th>
            <th>Descrição</th>
            <th>Tipo de Serviço</th>
            <th>Qtd.</th>
            <th>Unidade</th>
            <th>Preço</th>
            <th>Total</th>
            <th>Data</th>
    			</tr>
    		</thead>
    		<tbody>
          {% for expense in expenses %}
        			<tr>
                  <td><a href="{{ expense.get_absolute_url }}">{{expense.item}}</a></td>
                  <td>{{expense.description}}</td>
                  <td>{{expense.service_type}}</td>
                  <td>{{expense.quantity}}</td>
                  <td>{{expense.unit}}</td>
                  <td>{{expense.price}}</td>
                  <td>R$ {{expense.total}}</td>
                  <td>{{expense.created_at|date:"d/m/Y H:i A"}}</td>
              </tr>
          {% endfor %}
    		</tbody>
    	</table>
      {% else %}
      <p class="alert alert-warning">Sem itens na lista.</p>
    {% endif %}
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-md-6">
      <h3><b>Total:</b> {{ expenses|length }} despesa{{ expenses|pluralize }}</h3>
    </div>
  </div>
  {% pagination request paginator page_obj%}
</div>
{% endblock %}