core/urls.py
from django.conf.urls import url, include
from core import views

urlpatterns = [
    url(r'^$', views.IndexView, name='index'),
]

ong_joao_de_barro/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout
from core import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^entrar/$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^sair/$', logout, {'next_page': 'login'}, name='logout'),
    url(r'doacoes/', include('donations.urls', namespace='donations')),
    url(r'despesas/', include('expenses.urls', namespace='expenses')),
    url(r'conta/', include('accounts.urls', namespace='accounts')),
    url(r'usuarios/', include('users.urls', namespace='users')),
    url(r'^admin/', admin.site.urls),
]

users/urls.py
# coding=utf-8
from django.conf.urls import url
from users import views

urlpatterns = [
    url(r'^doadores/$', views.donors_list, name='donors_list'),
    url(r'^adicionar-doador/$', views.donors_add, name='donors_add'),
    url(r'^detalhes-doador/(?P<pk>[\w_-]+)/$', views.donors_detail,
        name='donors_detail'),
    url(r'^editar-doador/(?P<pk>[\w_-]+)/$', views.donors_update,
        name='donors_update'),
    url(r'^alunos/$', views.students_list, name='students_list'),
    url(r'^adicionar-aluno/$', views.students_add, name='students_add'),
    url(r'^detalhes-aluno/(?P<pk>[\w_-]+)/$', views.students_detail,
        name='students_detail'),
    url(r'^editar-aluno/(?P<pk>[\w_-]+)/$', views.students_update,
        name='students_update'),
    url(r'^funcionarios/$', views.employees_list, name='employees_list'),
    url(r'^adicionar-funcionario/$', views.employees_add,
        name='employees_add'),
    url(r'^detalhes-funcionario/(?P<pk>[\w_-]+)/$', views.employees_detail,
        name='employees_detail'),
    url(r'^editar-funcionario/(?P<pk>[\w_-]+)/$', views.employees_update,
        name='employees_update'),
]

users/models.py
# coding=utf-8
from django.db import models
from django.core.urlresolvers import reverse
from core.models import Address, PersonalInformations
from core.models import TimeStampedModel
from core.helpers.multiple_choices import SCHOLARITY, TIME, EMPLOYEES_TYPE


class Donors(Address, TimeStampedModel):
    name = models.CharField('Nome', max_length=100, unique=True)
    is_active = models.BooleanField('Ativo', help_text='Status do doador',
                                    default=True)
    email = models.EmailField('E-mail', unique=True, default='')
    phone = models.CharField('Telefone ', max_length=10, blank=True)
    cellphone = models.CharField('Celular', max_length=11, blank=True)
    comments = models.TextField('Observações', blank=True)

    def __str__(self):
        return str(self.name)

    class Meta:
        ordering = ['name']
        verbose_name = 'Doador'
        verbose_name_plural = 'Doadores'

    def get_absolute_url(self):
        return reverse('users:donors_detail', kwargs={'pk': self.pk})


class Students(Address, PersonalInformations, TimeStampedModel):
    scholarity = models.CharField('Escolaridade', choices=SCHOLARITY,
                                  max_length=100)
    school = models.CharField('Escola', blank=True, max_length=100)
    time = models.CharField('Período', choices=TIME, max_length=100)
    is_active = models.BooleanField('Ativo', help_text='Status do aluno',
                                    default=True)

    def __str__(self):
        return str(self.name + self.last_name)

    class Meta:
        ordering = ['name']
        verbose_name = 'Aluno'
        verbose_name_plural = 'Alunos'

    def get_absolute_url(self):
        return reverse('users:students_detail', kwargs={'pk': self.pk})


class Employees(Address, PersonalInformations, TimeStampedModel):
    bag_helped = models.BooleanField('Bolsa auxílio', default=False,
                                     help_text='O funcionário será remunerado\
                                     pelas atividades prestadas a ONG?')
    value = models.DecimalField('Valor', max_digits=6, decimal_places=2,
                                default=0)
    employees_type = models.CharField('Tipo de serviço', max_length=100,
                                      choices=EMPLOYEES_TYPE)
    is_active = models.BooleanField('Ativo', help_text='Status do aluno',
                                    default=True)

    def __str__(self):
        return str(self.name + self.last_name)

    class Meta:
        ordering = ['name']
        verbose_name = 'Funcionário'
        verbose_name_plural = 'Funcionários'

    def get_absolute_url(self):
        return reverse('users:employees_detail', kwargs={'pk': self.pk})

users/forms.py
# coding=utf-8
from django import forms
from .models import Donors, Students, Employees


class DonorsAddForm(forms.ModelForm):
    class Meta:
        model = Donors
        fields = ['is_active', 'name', 'email', 'phone', 'cellphone',
                  'address', 'number', 'complement', 'neighborhood',
                  'city', 'state', 'cep', 'comments']
        readonly_fields = ('created_at')


class StudentsAddForm(forms.ModelForm):
    class Meta:
        model = Students
        fields = ['is_active', 'name', 'last_name', 'date_of_birth', 'gender',
                  'mothers_name', 'fathers_name', 'rg', 'cpf', 'scholarity',
                  'school', 'time', 'occupation', 'civil_status',  'address',
                  'number', 'complement', 'neighborhood', 'city', 'state',
                  'cep', 'email', 'phone', 'cellphone', 'comments']
        readonly_fields = ('created_at')


class EmployeesAddForm(forms.ModelForm):
    class Meta:
        model = Employees
        fields = ['is_active', 'name', 'last_name', 'date_of_birth', 'gender',
                  'mothers_name', 'fathers_name', 'rg', 'cpf', 'occupation',
                  'bag_helped', 'value', 'employees_type', 'civil_status',
                  'address', 'number', 'complement', 'neighborhood', 'city',
                  'state', 'cep', 'email', 'phone', 'cellphone', 'comments']
        readonly_fields = ('created_at')

users/views.py
# coding=utf-8
from django.db.models import Q
from django.shortcuts import render
from django.views.generic import CreateView, UpdateView, DetailView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from users.models import Donors, Students, Employees
from users.forms import DonorsAddForm, StudentsAddForm, EmployeesAddForm


class DonorsListView(LoginRequiredMixin, ListView):
    template_name = 'users/donors_list.html'
    model = Donors
    context_object_name = 'donors'
    paginate_by = 10
    queryset = Donors.objects.all().order_by('-created_at')

    def get_queryset(self):
        queryset = Donors.objects.all().order_by('-created_at')
        q = self.request.GET.get('q', '')
        if q:
            queryset = queryset.filter(Q(name__icontains=q))
        elif self.request.GET.get('is_active') == 'True':
            queryset = queryset.filter(is_active=1)
        elif self.request.GET.get('is_active') == 'False':
            queryset = queryset.filter(is_active=0)
        return queryset


class DonorsCreateView(LoginRequiredMixin, CreateView):
    model = Donors
    form_class = DonorsAddForm


class DonorsUpdateView(LoginRequiredMixin, UpdateView):
    model = Donors
    template_name_suffix = '_update_form'
    fields = ['is_active', 'name', 'email', 'phone', 'cellphone', 'address',
              'number', 'complement', 'neighborhood', 'city', 'state', 'cep',
              'comments']


class DonorsDetailView(LoginRequiredMixin, DetailView):
    model = Donors
    context_object_name = 'donors'


class StudentsListView(LoginRequiredMixin, ListView):
    template_name = 'users/students_list.html'
    model = Students
    context_object_name = 'students'
    paginate_by = 10
    queryset = Students.objects.all().order_by('-created_at')

    def get_queryset(self):
        queryset = Students.objects.all().order_by('-created_at')
        q = self.request.GET.get('q', '')
        if q:
            queryset = queryset.filter(Q(name__icontains=q))
        elif self.request.GET.get('is_active') == 'True':
            queryset = queryset.filter(is_active=1)
        elif self.request.GET.get('is_active') == 'False':
            queryset = queryset.filter(is_active=0)
        return queryset


class StudentsCreateView(LoginRequiredMixin, CreateView):
    model = Students
    form_class = StudentsAddForm


class StudentsUpdateView(LoginRequiredMixin, UpdateView):
    model = Students
    template_name_suffix = '_update_form'
    fields = ['is_active', 'name', 'last_name', 'date_of_birth', 'gender',
              'mothers_name', 'fathers_name', 'rg', 'cpf', 'scholarity',
              'school', 'time', 'occupation', 'civil_status',  'address',
              'number', 'complement', 'neighborhood', 'city', 'state',
              'cep', 'email', 'phone', 'cellphone', 'comments']


class StudentsDetailView(LoginRequiredMixin, DetailView):
    model = Students
    context_object_name = 'students'


class EmployeesListView(LoginRequiredMixin, ListView):
    template_name = 'users/employees_list.html'
    model = Employees
    context_object_name = 'employees'
    paginate_by = 10
    queryset = Employees.objects.all().order_by('-created_at')

    def get_queryset(self):
        queryset = Employees.objects.all().order_by('-created_at')
        q = self.request.GET.get('q', '')
        if q:
            queryset = queryset.filter(Q(name__icontains=q))
        elif self.request.GET.get('is_active') == 'True':
            queryset = queryset.filter(is_active=1)
        elif self.request.GET.get('is_active') == 'False':
            queryset = queryset.filter(is_active=0)
        return queryset


class EmployeesCreateView(LoginRequiredMixin, CreateView):
    model = Employees
    form_class = EmployeesAddForm


class EmployeesUpdateView(LoginRequiredMixin, UpdateView):
    model = Employees
    template_name_suffix = '_update_form'
    fields = ['is_active', 'name', 'last_name', 'date_of_birth', 'gender',
              'mothers_name', 'fathers_name', 'rg', 'cpf', 'occupation',
              'bag_helped', 'value', 'employees_type', 'civil_status',
              'address', 'number', 'complement', 'neighborhood', 'city',
              'state', 'cep', 'email', 'phone', 'cellphone', 'comments']


class EmployeesDetailView(LoginRequiredMixin, DetailView):
    model = Employees
    context_object_name = 'employees'


donors_list = DonorsListView.as_view()
donors_add = DonorsCreateView.as_view()
donors_update = DonorsUpdateView.as_view()
donors_detail = DonorsDetailView.as_view()
students_list = StudentsListView.as_view()
students_add = StudentsCreateView.as_view()
students_update = StudentsUpdateView.as_view()
students_detail = StudentsDetailView.as_view()
employees_list = EmployeesListView.as_view()
employees_add = EmployeesCreateView.as_view()
employees_update = EmployeesUpdateView.as_view()
employees_detail = EmployeesDetailView.as_view()

users/templates/users/donors_detail.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %} Detalhes do doador | {{ block.super}} {% endblock title %}

{% block spacename %} Detalhes do doador {{object.item}} {% endblock spacename %}

{% block container %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6">
      <div class="panel-group">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title"> <a data-toggle="collapse" href="#collapseOne">
              <span class="fa fa-user"></span> Doador </a> </h4>
          </div>
          <div id="collapseOne" class="panel-collapse collapse in">
            <div class="panel-body">
              <div class="row">
                <table class="table table-user-information">
                  <tbody>
                    <tr>
                      <th class="text-justify"> Ativo </th>
                      {% if donors.is_active is True %}
                        <td><p class="glyphicon glyphicon-ok text-success"></p></td>
                      {% else %}
                        <td><p class="glyphicon glyphicon-remove text-danger"></p></td>
                      {% endif %}
                    </tr>
                    <tr>
                      <th class="col-md-3 text-justify"> Doador </th>
                      <td>{{ donors.name }}</td>
                    </tr>
                    <tr>
                      <th class="col-md-3 text-justify"> Email </th>
                      <td>{{ donors.email }}</td>
                    </tr>
                    <tr>
                      <th class="col-md-3 text-justify"> Telefone </th>
                      <td>{{ donors.phone }}</td>
                    </tr>
                    <tr>
                      <th class="col-md-3 text-justify"> Celular </th>
                      <td>{{ donors.cellphone }}</td>
                    </tr>
                    <tr>
                      <th class="col-md-3 text-justify"> Bolsa Auxílio </th>
                      <td>{{ donors.bag_helped }}</td>
                    </tr>
                    <tr>
                      <th class="col-md-3 text-justify"> Valor </th>
                      <td>{{ donors.value|default:"---" }}</td>
                    </tr>
                    <tr>
                      <th class="text-justify"> Endereço </th>
                      <td>{{ donors.address }}</td>
                    </tr>
                    <tr>
                      <th class="text-justify"> Número </th>
                      <td>{{ donors.number }} </td>
                    </tr>
                    <tr>
                      <th class="text-justify"> Bairro </th>
                      <td>{{ donors.neighborhood }} </td>
                    </tr>
                    <tr>
                      <th class="text-justify"> Cidade </th>
                      <td>{{ donors.city }} </td>
                    </tr>
                    <tr>
                      <th class="text-justify"> Estado </th>
                      <td>{{ donors.state }} </td>
                    </tr>
                    <tr>
                      <th class="text-justify"> Data </th>
                      <td>{{ donors.created_at|date:"d/m/Y H:i A" }}</td>
                    </tr>
                    <tr>
                      <th class="col-md-3 text-justify"> Observações </th>
                      <td>{{ donors.comments }}</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <!-- button back -->
      <form class="navbar-form navbar-right" action="." method="get">
        <a href="{% url 'users:donors_update' donors.pk %}">
          <a href="{% url 'users:donors_update' donors.pk %}">
            <button type="button" class="btn btn-primary btn-lg" style="width: 140px; height: 50px">
              <span class="glyphicon glyphicon-back"></span> Editar
            </button>
          </a>
        </a>
        <a href="{% url 'users:donors_list' %}">
          <a href="{% url 'users:donors_list' %}">
            <button type="button" class="btn btn-info btn-lg" style="width: 140px; height: 50px">
              <span class="glyphicon glyphicon-back"></span> Voltar
            </button>
          </a>
        </a>
      </form>
    </div>
  </div>
</div>
{% endblock %}

users/templates/users/donors_form.html
{% extends "base.html" %}

{% load bootstrap %}
{% load widget_tweaks %}

{% block title %} Adicionar Doador | {{ block.super}} {% endblock title %}

{% block spacename %} Adicionar Doador {% endblock spacename %}

{% block container %}
  <form class="form-horizontal col-sm-5" action="." method="POST">
    {% csrf_token %}
    {{ form|bootstrap_horizontal:'col-lg-4' }}
	  <div class="form-group">
      <div class="col-sm-10 col-sm-offset-9">
        <button type="submit" class="btn btn-primary"> Salvar </button>
      </div>
    </div>
  </form>
  <div class="col-md-7">
    <!-- button back -->
    <form class="navbar-form navbar-right" action="." method="get">
      <a href="{% url 'users:donors' %}">
        <button type="button" class="btn btn-info btn-lg" style="width: 190px; height: 50px">
          <span class="glyphicon glyphicon-back"></span> Voltar
        </button>
      </a>
    </form>
  </div>
{% endblock %}

users/templates/users/donors_list.html
{% extends "base.html" %}

{% load pagination %}

{% block title %} Lista de Doadores | {{ block.super}} {% endblock title %}

{% block spacename %} Lista de Doadores {% endblock spacename %}

{% block container %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <form class="navbar-form navbar-right" action="." method="get">
        <div class="col-md-12">
          <!-- add -->
          <a href="{% url 'users:donors_add' %}">
            <button id="new_customer" type="button" class="btn btn-primary">
              <span class="glyphicon glyphicon-plus"></span> Adicionar
            </button>
          </a>
          <!-- search form -->
          <form class="navbar-form navbar-left" role="search" action="{% url 'users:donors_list' %}">
  	        <div class="form-group">
	            <input name="q" type="text" class="form-control" placeholder="Pesquisar..." />
              <button type="submit" class="btn btn-success form-control"><span class="glyphicon glyphicon-search"></span></button>
            </div>
          </form>
          <br><br>
          <!-- Search links-->
          <ul class="list-inline text-right">
            <li><a href="{% url 'users:donors_list' %}"><span class="fa fa-star status-aprovado"></span> Todos</a></li>
            <li><a href="?is_active=True" name="frue"><span class="glyphicon glyphicon-ok-sign ok text-success"></span> Ativos </a></li>
            <li><a href="?is_active=False" name="false"><span class="glyphicon glyphicon-ok-sign ok text-danger"></span> Desativados </a></li>
          </ul>
        </div>
      </form>
    </div>
    <div class="col-md-12">
      <hr/>
    </div>
    <div class="col-md-12">
      {% if donors %}
      	<table class="table table-bordered">
      		<thead>
      			<tr>
      				<th>Doador</th>
              <th>Ativo</th>
              <th>Endereço</th>
              <th>Número</th>
              <th>Bairro</th>
              <th>Cidade</th>
              <th>Estado</th>
              <th>Data</th>
      			</tr>
      		</thead>
      		<tbody>
            {% for donor in donors %}
          			<tr>
                    <td><a href="{{ donor.get_absolute_url }}">{{donor.name}}</a></td>
                    {% if donor.is_active is True %}
                      <td><p class="glyphicon glyphicon-ok text-success"></p></td>
                    {% else %}
                      <td><p class="glyphicon glyphicon-remove text-danger"></p></td>
                    {% endif %}
                    <td>{{donor.address}}</td>
                    <td>{{donor.number}}</td>
                    <td>{{donor.neighborhood}}</td>
                    <td>{{donor.city}}</td>
                    <td>{{donor.state}}</td>
                    <td>{{donor.created_at|date:"d/m/Y H:i A"}}</td>
                </tr>
            {% endfor %}
      		</tbody>
      	</table>
        {% else %}
        <p class="alert alert-warning">Sem itens na lista.</p>
      {% endif %}
    </div>
  </div>
  <hr>
  <div>
    <h3><b>Total:</b> {{ donors|length }} doadore{{ donors|length|pluralize }}</h3>
  </div>
  {% pagination request paginator page_obj%}
</div>
{% endblock %}

users/templates/users/donors_update_form.html
{% extends "base.html" %}

{% load bootstrap %}
{% load widget_tweaks %}

{% block title %} Atualizar dados | {{ block.super}} {% endblock title %}

{% block spacename %} Atualizar dados {% endblock spacename %}

{% block container %}
  <form class="form-horizontal col-sm-5" action="." method="POST">
    {% csrf_token %}
    {{ form|bootstrap_horizontal:'col-lg-4' }}
	  <div class="form-group">
      <div class="col-sm-10 col-sm-offset-9">
        <button type="submit" class="btn btn-primary"> Salvar </button>
      </div>
    </div>
  </form>
  <div class="col-md-7">
    <!-- button back -->
    <form class="navbar-form navbar-right" action="." method="get">
      <a href="{% url 'users:donors_list' %}">
        <button type="button" class="btn btn-info btn-lg" style="width: 190px; height: 50px">
          <span class="glyphicon glyphicon-back"></span> Cancelar edição
        </button>
      </a>
    </form>
  </div>
{% endblock %}

users/templates/users/employees_detail.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %} Detalhes do {{ employees.employees_type }} | {{ block.super}} {% endblock title %}

{% block spacename %} Detalhes de {{ employees.name }} {{ employees.last_name }} {% endblock spacename %}

{% block container %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6">
      <div class="panel-group">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title"> <a data-toggle="collapse" href="#collapseOne">
              <span class="fa fa-user"></span> Funcionário </a> </h4>
          </div>
          <div id="collapseOne" class="panel-collapse collapse in">
            <div class="panel-body">
              <div class="row">
                <table class="table table-user-information">
                  <tbody>
                    <tr>
                      <th class="text-justify"> Ativo </th>
                      {% if employees.is_active is True %}
                        <td><p class="glyphicon glyphicon-ok text-success"></p></td>
                      {% else %}
                        <td><p class="glyphicon glyphicon-remove text-danger"></p></td>
                      {% endif %}
                    </tr>
                    <tr>
                      <th class="col-md-3 text-justify"> Nome </th>
                      <td>{{ employees.name }}</td>
                    </tr>
                    <tr>
                      <th class="col-md-3 text-justify"> Sobrenome </th>
                      <td>{{ employees.last_name }}</td>
                    </tr>
                    <tr>
                      <th class="col-md-3 text-justify"> Email </th>
                      <td>{{ employees.email }}</td>
                    </tr>
                    <tr>
                      <th class="col-md-3 text-justify"> Telefone </th>
                      <td>{{ employees.phone }}</td>
                    </tr>
                    <tr>
                      <th class="col-md-3 text-justify"> Celular </th>
                      <td>{{ employees.cellphone }}</td>
                    </tr>
                    <tr>
                      <th class="col-md-3 text-justify"> Nascimento </th>
                      <td>{{ employees.date_of_birth }}</td>
                    </tr>
                    <tr>
                      <th class="col-md-3 text-justify"> Gênero </th>
                      <td>{{ employees.gender }}</td>
                    </tr>
                    <tr>
                      <th class="col-md-3 text-justify"> Mãe </th>
                      <td>{{ employees.mothers_name }}</td>
                    </tr>
                    <tr>
                      <th class="col-md-3 text-justify"> Pai </th>
                      <td>{{ employees.fathers_name }}</td>
                    </tr>
                    <tr>
                      <th class="col-md-3 text-justify"> RG </th>
                      <td>{{ employees.rg }}</td>
                    </tr>
                    <tr>
                      <th class="col-md-3 text-justify"> CPF </th>
                      <td>{{ employees.cpf }}</td>
                    </tr>
                    <tr>
                      <th class="col-md-3 text-justify"> Bolsa Auxílio </th>
                      {% if employees.bag_helped is True %}
                        <td><p class="glyphicon glyphicon-ok text-success"></p></td>
                      {% else %}
                        <td><p class="glyphicon glyphicon-remove text-danger"></p></td>
                      {% endif %}
                    </tr>
                    <tr>
                      <th class="col-md-3 text-justify"> Valor </th>
                      <td>{{ employees.value }}</td>
                    </tr>
                    <tr>
                      <th class="col-md-3 text-justify"> Tipo de serviço </th>
                      <td>{{ employees.employees_type }}</td>
                    </tr>
                    <tr>
                      <th class="col-md-3 text-justify"> Profissão </th>
                      <td>{{ employees.occupation }}</td>
                    </tr>
                    <tr>
                      <th class="col-md-3 text-justify"> Estado civil </th>
                      <td>{{ employees.civil_status }}</td>
                    </tr>
                    <tr>
                      <th class="text-justify"> Endereço </th>
                      <td>{{ employees.address }}</td>
                    </tr>
                    <tr>
                      <th class="text-justify"> Número </th>
                      <td>{{ employees.number }} </td>
                    </tr>
                    <tr>
                      <th class="text-justify"> Complemento </th>
                      <td>{{ employees.complement }} </td>
                    </tr>
                    <tr>
                      <th class="text-justify"> Bairro </th>
                      <td>{{ employees.neighborhood }} </td>
                    </tr>
                    <tr>
                      <th class="text-justify"> Cidade </th>
                      <td>{{ employees.city }} </td>
                    </tr>
                    <tr>
                      <th class="text-justify"> Estado </th>
                      <td>{{ employees.state }} </td>
                    </tr>
                    <tr>
                      <th class="text-justify"> CEP </th>
                      <td>{{ employees.cep }} </td>
                    </tr>
                    <tr>
                      <th class="text-justify"> Data </th>
                      <td>{{ employees.created_at|date:"d/m/Y H:i A" }}</td>
                    </tr>
                    <tr>
                      <th class="col-md-3 text-justify"> Observações </th>
                      <td>{{ employees.comments }}</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <!-- button back -->
      <form class="navbar-form navbar-right" action="." method="get">
        <a href="{% url 'users:employees_update' employees.pk %}">
          <a href="{% url 'users:employees_update' employees.pk %}">
            <button type="button" class="btn btn-primary btn-lg" style="width: 140px; height: 50px">
              <span class="glyphicon glyphicon-back"></span> Editar
            </button>
          </a>
        </a>
        <a href="{% url 'users:employees_list' %}">
          <a href="{% url 'users:employees_list' %}">
            <button type="button" class="btn btn-info btn-lg" style="width: 140px; height: 50px">
              <span class="glyphicon glyphicon-back"></span> Voltar
            </button>
          </a>
        </a>
      </form>
    </div>
  </div>
</div>
{% endblock %}

users/templates/users/employees_list.html
{% extends "base.html" %}

{% load pagination %}

{% block title %} Lista de Funcionários | {{ block.super}} {% endblock title %}

{% block spacename %} Lista de Funcionários {% endblock spacename %}

{% block container %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <form class="navbar-form navbar-right" action="." method="get">
        <div class="col-md-12">
          <!-- add -->
          <a href="{% url 'users:employees_add' %}">
            <button id="new_customer" type="button" class="btn btn-primary">
              <span class="glyphicon glyphicon-plus"></span> Adicionar
            </button>
          </a>
          <!-- search form -->
          <form class="navbar-form navbar-left" role="search" action="{% url 'users:employees_list' %}">
  	        <div class="form-group">
	            <input name="q" type="text" class="form-control" placeholder="Pesquisar..." />
              <button type="submit" class="btn btn-success form-control"><span class="glyphicon glyphicon-search"></span></button>
            </div>
          </form>
          <br><br>
          <!-- Search links-->
          <ul class="list-inline text-right">
            <li><a href="{% url 'users:employees_list' %}"><span class="fa fa-star status-aprovado"></span> Todos</a></li>
            <li><a href="?is_active=True" name="frue"><span class="glyphicon glyphicon-ok-sign ok text-success"></span> Ativos </a></li>
            <li><a href="?is_active=False" name="false"><span class="glyphicon glyphicon-ok-sign ok text-danger"></span> Desativados </a></li>
          </ul>
        </div>
      </form>
    </div>
    <div class="col-md-12">
      <hr/>
    </div>
    <div class="col-md-12">
      {% if employees %}
      	<table class="table table-bordered">
      		<thead>
      			<tr>
      				<th>Funcionário</th>
              <th>Ativo</th>
              <th>Data de nascimento</th>
              <th>Email</th>
              <th>Bolsa Auxílio</th>
              <th>Valor</th>
              <th>Celular</th>
              <th>Data</th>
      			</tr>
      		</thead>
      		<tbody>
            {% for employee in employees %}
          			<tr>
                    <td><a href="{{ employee.get_absolute_url }}">{{employee.name}} {{employee.last_name}}</a></td>
                    {% if employee.is_active is True %}
                      <td><p class="glyphicon glyphicon-ok text-success"></p></td>
                    {% else %}
                      <td><p class="glyphicon glyphicon-remove text-danger"></p></td>
                    {% endif %}
                    <td>{{employee.date_of_birth|date:"d/m/Y"}}</td>
                    <td>{{employee.email}}</td>
                    <td>{{employee.bag_helped}}</td>
                    <td>{{employee.value}}</td>
                    <td>{{employee.cellphone}}</td>
                    <td>{{employee.created_at|date:"d/m/Y H:i A"}}</td>
                </tr>
            {% endfor %}
      		</tbody>
      	</table>
        {% else %}
        <p class="alert alert-warning">Sem itens na lista.</p>
      {% endif %}
    </div>
  </div>
  <hr>
  <div>
    <h3><b>Total:</b> {{ employees|length }} funcionário{{ employees|length|pluralize }}</h3>
  </div>
  {% pagination request paginator page_obj%}
</div>
{% endblock %}