accounts/urls.py
# coding=utf-8
from django.conf.urls import url
from accounts import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^registro/$', views.register, name='register'),
    url(r'^alterar-dados/$', views.update_user, name='update_user'),
    url(r'^alterar-senha/$', views.update_password, name='update_password'),
    # url(r'^(?P<pk>[\w_-]+)/$', views.user_detail, name='user_detail'),
]

core/urls.py
from django.conf.urls import url, include
from core import views

urlpatterns = [
    url(r'^$', views.IndexView, name='index'),
]

donations/urls.py
from django.conf.urls import url, include
from donations import views

urlpatterns = [
    url(r'^$', views.donations, name='donation'),
    url(r'^adicionar/$', views.donations_add, name='donation_add'),
    url(r'^detalhes/(?P<pk>[\w_-]+)/$', views.donations_detail,
        name='donation_detail'),
    url(r'^editar/(?P<slug>[\w_-]+)/$', views.donations_update,
        name='donation_update'),
]

expenses/urls.py
from django.conf.urls import url, include
from expenses import views

urlpatterns = [
    url(r'^$', views.expenses, name='expense'),
    url(r'^adicionar/$', views.expenses_add, name='expense_add'),
    url(r'^detalhes/(?P<pk>[\w_-]+)/$', views.expenses_detail,
        name='expense_detail')
]

ong_joao_de_barro/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout
from core import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^entrar/$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^sair/$', logout, {'next_page': 'login'}, name='logout'),
    url(r'doacoes/', include('donations.urls', namespace='donations')),
    url(r'despesas/', include('expenses.urls', namespace='expenses')),
    url(r'conta/', include('accounts.urls', namespace='accounts')),
    url(r'usuarios/', include('users.urls', namespace='users')),
    url(r'^admin/', admin.site.urls),
]

users/urls.py
# coding=utf-8
from django.conf.urls import url
from users import views

urlpatterns = [
    url(r'^doadores/$', views.donors_list, name='donors_list'),
    url(r'^adicionar-doador/$', views.donors_add, name='donors_add'),
    url(r'^detalhes-doador/(?P<pk>[\w_-]+)/$', views.donors_detail,
        name='donors_detail'),
    url(r'^editar-doador/(?P<pk>[\w_-]+)/$', views.donors_update,
        name='donors_update'),
    url(r'^alunos/$', views.students_list, name='students_list'),
    url(r'^adicionar-aluno/$', views.students_add, name='students_add'),
    url(r'^detalhes-aluno/(?P<pk>[\w_-]+)/$', views.students_detail,
        name='students_detail'),
    url(r'^editar-aluno/(?P<pk>[\w_-]+)/$', views.students_update,
        name='students_update'),
    url(r'^funcionarios/$', views.employees_list, name='employees_list'),
    url(r'^adicionar-funcionario/$', views.employees_add,
        name='employees_add'),
    url(r'^detalhes-funcionario/(?P<pk>[\w_-]+)/$', views.employees_detail,
        name='employees_detail'),
    url(r'^editar-funcionario/(?P<pk>[\w_-]+)/$', views.employees_update,
        name='employees_update'),
]

core/models.py
# coding=utf-8
from django.db import models
from core.helpers.multiple_choices import UF, CIVIL_STATUS, GENDER


class TimeStampedModel(models.Model):
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    modified_at = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        abstract = True


class Address(models.Model):
    address = models.CharField('Endereço', max_length=100, blank=True)
    number = models.IntegerField('Número')
    complement = models.CharField('Complemento', max_length=100, blank=True)
    neighborhood = models.CharField('Bairro', max_length=100, blank=True)
    city = models.CharField('Cidade', max_length=100, blank=True)
    state = models.CharField('Estado', max_length=16, choices=UF, blank=True)
    cep = models.CharField('CEP', max_length=8, blank=True)

    class Meta:
            abstract = True


class PersonalInformations(models.Model):
    name = models.CharField('Nome', max_length=50)
    last_name = models.CharField('Sobrenome', max_length=50)
    email = models.EmailField('E-mail', unique=True)
    date_of_birth = models.DateField('Data de nascimento', auto_now=False,
                                     help_text='Inserir data no seguinte\
                                     formato __/__/____')
    gender = models.CharField('Gênero', choices=GENDER, max_length=14)
    civil_status = models.CharField('Estado civil', choices=CIVIL_STATUS,
                                    max_length=14)
    mothers_name = models.CharField('Mãe', max_length=100)
    fathers_name = models.CharField('Pai', blank=True, max_length=100)
    occupation = models.CharField('Profissão', max_length=70)
    rg = models.CharField('RG', unique=True, max_length=9)
    cpf = models.CharField('CPF', unique=True, max_length=11)
    phone = models.CharField('Telefone ', max_length=10, blank=True)
    cellphone = models.CharField('Celular', max_length=11, blank=True)
    comments = models.TextField('Observações', blank=True)

    class Meta:
        abstract = True

core/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from django.views.generic import TemplateView, CreateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model


User = get_user_model()


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'index.html'


index = IndexView.as_view()

core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pt">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

  	<title>{% block title %} ONG João de Barro {% endblock %}</title>

    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet"> <!-- Bootstrap Core CSS -->
    <link href="{% static 'distt/css/sb-admin-2.min.css' %}" rel="stylesheet"> <!-- Custom CSS -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css"> <!-- Custom Fonts -->
</head>

<body>
  <div id="wrapper">
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="index.html">ONG - João de Barro</a>
      </div>
      <ul class="nav navbar-top-links navbar-right">
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#"> Olá {{ user }} <i class="fa fa-caret-down"></i></a>
          <ul class="dropdown-menu dropdown-user">
            <li><a href="{% url 'accounts:index' %}"><i class="fa fa-user fa-fw"></i> User Profile</a>
            </li>
            <li class="divider"></li>
            <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out fa-fw"></i> Sair </a></li>
          </ul>
        </li>
      </ul>
      <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
          <ul class="nav" id="side-menu">
            <br>
            <li><a href="{% url 'index' %}"><i class="fa fa-dashboard fa-fw"></i> Dashboard </a></li>
            <li><a href="{% url 'donations:donation' %}"><i class="glyphicon glyphicon-gift"></i> Doações </a></li>
            <li><a href="{% url 'expenses:expense' %}"><i class="glyphicon glyphicon-list-alt"></i> Despesas </a></li>
            <li><a href="#"><i class="fa fa-users"></i> Consultar <span class="fa arrow"></span></a>
              <ul class="nav nav-second-level">
                <li><a href="{% url 'users:students_list' %}"> Alunos </a></li>
                <li><a href="{% url 'users:donors_list' %}"> Doadores </a></li>
                <li><a href="{% url 'users:employees_list' %}"> Funcionários </a></li>
              </ul>
            </li>
            <li><a href="#"><i class="fa fa-user"></i> Minha conta <span class="fa arrow"></span></a>
              <ul class="nav nav-second-level">
                <li><a href="{% url 'accounts:index' %}"> Informações de perfil </a></li>
                <li><a href="{% url 'accounts:update_user' %}"> Alterar meus dados </a></li>
                <li><a href="{% url 'accounts:update_password' %}"> Alterar senha </a></li>
              </ul>
            </li>
            <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out fa-fw"></i> Sair </a></li>
          </ul>
        </div>
      </div>
    </nav>

    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">{% block spacename %}{% endblock spacename %}</h1>
            </div>
        </div>
        <div class="row">
            {% block container %} {% endblock %}
        </div>
    </div>
  </div>

  <script src="{% static 'jquery/jquery.min.js' %}"></script> <!-- jQuery -->
  <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script> <!-- Bootstrap Core JavaScript -->
  <script src="{% static 'metisMenu/metisMenu.min.js' %}"></script> <!-- Metis Menu Plugin JavaScript -->
  <script src="{% static 'distt/js/sb-admin-2.min.js' %}"></script> <!-- Custom Theme JavaScript -->

</body>

</html>

core/templates/index.html
{% extends "base.html" %}

{% block spacename %} Dashboard {% endblock spacename %}

{% block container %}
    <div class="jumbotron page-header">
      <h1>Django ONG João de Barro</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      <p><a class="btn btn-primary">Saiba mais</a></p>
    </div>
{% endblock %}

core/templates/login.html
<!DOCTYPE html>
{% load static %}
{% load widget_tweaks %}
<html lang="pt">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

  	<title>{% block title %} Entrar {% endblock %}</title>
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet"> <!-- Bootstrap Core CSS -->
    <link href="{% static 'distt/css/sb-admin-2.css' %}" rel="stylesheet"> <!-- Custom CSS -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css"> <!-- Custom Fonts -->
</head>

<body>
  <div class="container-fluid">
  	<div class="row">
      <div class="col-md-6">
    		<div class="col-md-6 col-md-offset-9 ">
    		  <div class="page-header text-center">
            <h1>Entrar</h1>
          </div>
          <form class="form-horizontal" method="post">
            {% csrf_token %}
            {# lista de erro que não está atrelada a determinado campo #}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error}}
              </div>
            {% endfor %}
            <fieldset>
              <div class="form-group {% if form.username.errors%} has-error {% endif %}">
                <label for="{{ form.username.auto_id }}" class="col-md-2 control-label">{{ form.username.label }}</label>
                <div class="col-md-9">
                  {% render_field form.username class="form-control"%}
                  {% for error in form.username.errors %}
                    <span class="help-block"> {{ error }} </span>
                  {% endfor %}
                </div>
              </div>
              <div class="form-group {% if form.password.errors%} has-error {% endif %}">
                <label for="{{ form.password.auto_id }}" class="col-md-2 control-label">{{ form.password.label }}</label>
                <div class="col-md-9">
                  {% render_field form.password class="form-control"%}
                  {% for error in form.password.errors %}
                    <span class="help-block"> {{ error }} </span>
                  {% endfor %}
                </div>
              </div>
              <div class="form-group">
                <div class="col-md-9 col-md-offset-3">
                  <button type="submit" class="btn btn-primary">Enviar</button>
                </div>
              </div>
            </fieldset>
          </form>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

core/templates/pagination.html
<div class="row">
  <div class="col-md-12">
    <ul class="pagination">
        {% for page in paginator.page_range %}
          <li {% if page_obj.number == page %} class="active" {% endif %}>
            <a href="?page={{ page }}{{ getvars }}"> {{ page }}</a></li>
        {% endfor %}
    </ul>
  </div>
</div>